# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.6"
  - "3.5"
  - "2.7"

env:
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.10,<1.11"
  - DJANGO="https://github.com/django/django/archive/master.tar.gz"


matrix:
  fast_finish: true
  exclude:
    - python: "2.7"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -q $DJANGO
  - pip install -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: coverage run --source django_model_sync runtests.py

